package io.complete.security;

import java.util.ArrayList;

public class SecurityHandler {

	public static ArrayList<String> loggedOut = new ArrayList<String>();
	
	public static ArrayList<String> getLoggedOutPlayers(){
		return loggedOut;
	}
	
	/**
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * FINISH SECURITY SYSTEM WHEN HOME
	 * 
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * DOWNLOAD BASE & KITS SRC WHEN HOME
	 * 
	 * ALSO SEND HIM JANITOR AND SEE IF HE CAN DECOMPILE
	 */


}
